name: Use Custom Project Standardizer

on:
  workflow_dispatch:

jobs:
  standardize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Project Standardizer
        id: standardize
        uses: pradeepathirumurthi70-star/caj@v1
        with:
          project-name: "My Backend Service"

      - name: Display Result
        run: |
          echo "Action executed successfully!"
          echo "Formatted Message: ${{ steps.standardize.outputs.formatted-message }}"
